[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SHL-api"
version = "0.1.0"
description = "Api for SHL project"
authors = [
    {name = "Devang Bawri", email = "devangbawri@gmail.com"},
]